### ISSUE TITLE
`.lead` in Glyphwise different results with and without linebreak

### ISSUE THREAD

**Issue by Mark2Mark** [coldtype/coldtype#159]
```python
Glyphwise(
    "Foo\nBar",
    lambda g: Style(
        fnt,
        100,
    ),
)
.lead(10)
```

When you plug in the strings a: "Foo\nBar" and b: "Foo Bar", b will cause the text to form a downwards facing staircase, while a will just have a normal increased leading between the 2 lines.

Is that intentional? It is the same with `.xalign`.

**Comment by stenson** [comment]
It is intentional as there's a `multiline` keyword that you can pass to `Glyphwise` to make it always return nested lines from Glyphwise, regardless of text input, i.e.

```python
(Glyphwise(
    "A B",
    lambda g: Style(
        Font.JBMono(),
        100,
    ),
    multiline=True
)
.lead(10))
```

will return this nested structure:

```
<®:P:/1...>
 | <®:P:/3...>
 | - <®:P:RecordingPen(15mvs) {frame=Rect(0.00,0.00,60.00,73.00),glyphName=A}>
 | - <®:P: {frame=Rect(60.00,0.00,60.00,73.00),glyphName=space}>
 | - <®:P:RecordingPen(21mvs) {frame=Rect(120.00,0.00,60.00,73.00),glyphName=B}>
```

though without the multiline, you get this unnested structure:

```
<®:P:/3...>
 - <®:P:RecordingPen(15mvs) {frame=Rect(0.00,20.00,60.00,73.00),glyphName=A}>
 - <®:P: {frame=Rect(60.00,10.00,60.00,73.00),glyphName=space}>
 - <®:P:RecordingPen(21mvs) {frame=Rect(120.00,0.00,60.00,73.00),glyphName=B}>
```

I could see there being an argument to have multiline be `True` by default, though at the moment it's `False` for one-line text inputs by default. The staircase effect you're noticing and the `xalign` result all come from the same behavior, as they're treating the individual glyphs as the "lines." An alternative to setting the multiline keyword would be to call `.up` on the result before running methods like `xalign` or `lead`, as that would "raise" the nesting level of the result, pushing the un-nested glyphs into their own line, like this:

```
(Glyphwise(
    "A B",
    lambda g: Style(
        Font.JBMono(),
        100,
    ),
    multiline=False
)
.up()
.lead(10))
```

```
<®:P:/1...>
 | <®:P:/3...>
 | - <®:P:RecordingPen(15mvs) {frame=Rect(0.00,0.00,60.00,73.00),glyphName=A}>
 | - <®:P: {frame=Rect(60.00,0.00,60.00,73.00),glyphName=space}>
 | - <®:P:RecordingPen(21mvs) {frame=Rect(120.00,0.00,60.00,73.00),glyphName=B}>
```

**Comment by stenson** [comment]
Happy to help! Yeah I can close it out
