### ISSUE TITLE
Viewer window doesn't pop up

### ISSUE THREAD

**Issue by flatpickles** [coldtype/coldtype#71]
Using a fresh Python 3.9 virtual environment, I can't seem to get the viewer to appear. I get through the installation just fine with no errors, and when I run `coldtype demo` I see the following in my terminal:
> ... watching /opt/homebrew/lib/python3.9/site-packages/coldtype/demo/demo.py for changes ...

... but alas I see no Coldtype viewer. I'm on a M1 Mac, running Big Sur (11.4). I've seen the viewer pop up as expected on another Mac with an Intel chip (Big Sur 11.6), so I'm worried it's an Apple chip thing, but who's to say.

I'm about to update to Monterey and will try again after that, but assuming that won't make a difference, I'd love some troubleshooting ideas. Thanks!!

**Comment by stenson** [comment]
Thanks for trying it out, @flatpickles, and sorry it's not working! My guess is that this is the same issue as https://github.com/goodhertz/coldtype/issues/70, which comes down to some missing pypi wheels for arm (m1) versions of `glfw` and `freetype`, two key dependencies for the viewer. I don't yet have access to an m1 computer (one on the way), so I can't offer any direct help, but I've heard from a couple people that they've been able to get coldtype running on m1, either by using a rosetta-mode python (i.e. they installed a python that doesn't have a arm version and so only installs rosetta-bridge x86 wheels from pypi)

All that said, I'm not sure why you'd be seeing a path into your globally-installed python3.9 directory if you're running coldtype in a virtualenv — on my computer I get a:

```
... watching venv/lib/python3.9/site-packages/coldtype/demo/demo.py for changes ...
```

which points into the `venv` directory as a relative path (rather than the global `/opt` you've got). That could easily come down to something about m1, but it's also possible you installed coldtype into your global python site-packages and the command-line is preferring that one over the venv version (to fix that, I think you just need to `python3.9 -m pip uninstall coldtype` with no virtual env activated)

If you are able, could you try the solution outlined here https://github.com/goodhertz/coldtype/issues/70#issuecomment-949077417, about installing an older non-arm python and using that to make a venv?

**Comment by stenson** [comment]
think the m1 situation has resolved itself (since new binaries have been released for dependencies), so going to close this one — if you're still using coldtype & still having trouble on m1, let me know!
