### ISSUE TITLE
Steps to circumvent `segmentation fault` (likely on an M1/ARM Mac)

### ISSUE THREAD

**Issue by Mark2Mark** [coldtype/coldtype#78]
(Short summary of #70 )

When you see the `segmentation fault` on running a `coldtype {filename.py}`, find the `glfwskia.py` file.
Mine was in `venv/lib/python3.9/site-packages/coldtype/renderer/winman/glfwskia.py`

Somewhere around line 236 (state of Coldtype v0.7.5) it says:
```py
if pin:
     work_rect = Rect
```

change that to:

```py
if pin and False: # changed to prevent segmentation fault
    work_rect = Rect
```

This bypasses the following code which seems to be not needed, but may have caused the error.

Since these steps create a Coldtype customization on your machine, you need to re-do this after each install or update of Coldtype.

**Comment by stenson** [comment]
Thanks for noting this! I'm going to release a new version this week (0.7.6) that'll have a workaround for this, if you pass `-wp 0` (i.e. ``--window-pin=0``), i.e. `coldtype demo -wp 0`. The part you're short-circuiting with the `pin and False` isn't unnecessary, it's just not essential (the "window-pin" feature is described here: https://coldtype.goodhertz.com/cheatsheets/viewer.html?pin#command-line-window-modifications), so the `-wp 0` is just a way to say, don't attempt to pin the window, so that code won't be hit
